version: "3.5"

networks:
    nats:
        name: nats

services:
    nats:
        container_name: Flotilla-NATS
        image: 'nats:latest'
        expose:
            - "4222"
        ports:
            - 4222:4222
            - 6222:6222
            - 8222:8222
        networks: 
            - "nats"

    
    status:
        container_name: Flotilla-Status
        build:
            context: .
            dockerfile: dockerfile
        image: ximidar/flotilla:latest
        command: status start
        networks: 
            - "nats"
        depends_on: 
            - "nats"

    file_manager:
        container_name: Flotilla-File-Manager
        build: 
            context: .
            dockerfile: dockerfile
        image: ximidar/flotilla:latest
        depends_on:
            - "status"
            - "nats"
        volumes:
            - ~/gcode:/etc/flotilla/gcode
        command: ffm start
        networks: 
            - "nats"
    
    comm:
        container_name: Flotilla-Commango
        build:
            context: .
            dockerfile: dockerfile
        image: ximidar/flotilla:latest
        depends_on: 
            - "status"
            - "nats"
        volumes: 
            - /dev:/dev
        command: comm start
        networks: 
            - "nats"
    
    # fake_printer:
    #     container_name: Fake-Printer
    #     build:
    #         context: ./BuildResources/Test/FakeSerialDevice
    #         dockerfile: dockerfile
    #     image: flotilla-fake-printer:latest
    #     depends_on: 
    #         - "comm"
    #     volumes:
    #         - /dev:/dev 

    flotilla_web:
        container_name: Flot-Web
        build:
            context: .
            dockerfile: dockerfile
        image: flotilla_web:latest
        depends_on: 
            - "status"
            - "nats"
        ports:
            - "3000:3000"
        expose: 
            - 3000
        command: api start
        networks: 
            - "nats"
    
    # State Keeping
    # redis:
    #     container_name: redis
    #     image: redis:latest

