version: "3.5"

networks:
    nats:
        name: nats

services:
    nats:
        container_name: Flotilla-NATS
        image: 'nats:latest'
        expose:
            - "4222"
        ports:
            - 4222:4222
            - 6222:6222
            - 8222:8222
        networks: 
            - "nats"

    
    status:
        container_name: Flotilla-Status
        build:
            context: ./FlotillaStatus/
            dockerfile: dockerfile
        image: flotilla-status:latest
        volumes: 
            - ./FlotillaStatus:/home/flotilla/FlotillaStatus
        command: bash -c "go mod download && make serve"
        networks: 
            - "nats"
        depends_on: 
            - "nats"

    file_manager:
        container_name: Flotilla-File-Manager
        build: 
            context: ./Flotilla_File_Manager/
            dockerfile: dockerfile
        image: flotilla-file-manager:latest
        depends_on:
            - "status"
            - "nats"
        volumes:
            - /home/ximidar/gcode:/etc/flotilla/gcode
            - ./Flotilla_File_Manager:/home/flotilla/Flotilla_File_Manager
        command: bash -c "go mod download && make serve"
        networks: 
            - "nats"
    
    comm:
        container_name: Flotilla-Commango
        build:
            context: ./Commango
            dockerfile: dockerfile
        image: flotilla-commango:latest
        depends_on: 
            - "status"
            - "nats"
        volumes: 
            - /dev:/dev
            - ./Commango:/home/flotilla/Commango
        command: bash -c "go mod download && make serve"
        networks: 
            - "nats"
    
    # fake_printer:
    #     container_name: Fake-Printer
    #     build:
    #         context: ./BuildResources/Test/FakeSerialDevice
    #         dockerfile: dockerfile
    #     image: flotilla-fake-printer:latest
    #     depends_on: 
    #         - "comm"
    #     volumes:
    #         - /dev:/dev 

    flotilla_web:
        container_name: Flot-Web
        build:
            context: ./FlotillaWebAPI
            dockerfile: dockerfile
        image: flotilla_web:latest
        depends_on: 
            - "status"
            - "nats"
        volumes: 
            - ./FlotillaWebAPI:/home/flotilla/FlotillaWebAPI
        ports:
            - "3000:3000"
        expose: 
            - 3000
        command: bash -c "go mod download && make serve"
        networks: 
            - "nats"
    
    # State Keeping
    # redis:
    #     container_name: redis
    #     image: redis:latest

