// Code generated by protoc-gen-go. DO NOT EDIT.
// source: FileStructures.proto

package FileStructures

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileAction_Option int32

const (
	// SelectFile will Select a file
	FileAction_SelectFile FileAction_Option = 0
	// GetFileStructure will get the JSON representation of the current file structure
	FileAction_GetFileStructure FileAction_Option = 1
	// AddFile will add a file to the file structure
	FileAction_AddFile FileAction_Option = 2
	// MoveFile will move a file from one place to another
	FileAction_MoveFile FileAction_Option = 3
	// DeleteFile will delete a file
	FileAction_DeleteFile FileAction_Option = 4
)

var FileAction_Option_name = map[int32]string{
	0: "SelectFile",
	1: "GetFileStructure",
	2: "AddFile",
	3: "MoveFile",
	4: "DeleteFile",
}

var FileAction_Option_value = map[string]int32{
	"SelectFile":       0,
	"GetFileStructure": 1,
	"AddFile":          2,
	"MoveFile":         3,
	"DeleteFile":       4,
}

func (x FileAction_Option) String() string {
	return proto.EnumName(FileAction_Option_name, int32(x))
}

func (FileAction_Option) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_718985211eb12c86, []int{0, 0}
}

// FileAction is an object to convey what action you want
// the File system to take
type FileAction struct {
	Action               FileAction_Option `protobuf:"varint,1,opt,name=Action,proto3,enum=FileStructures.FileAction_Option" json:"Action,omitempty"`
	Path                 string            `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FileAction) Reset()         { *m = FileAction{} }
func (m *FileAction) String() string { return proto.CompactTextString(m) }
func (*FileAction) ProtoMessage()    {}
func (*FileAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_718985211eb12c86, []int{0}
}

func (m *FileAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileAction.Unmarshal(m, b)
}
func (m *FileAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileAction.Marshal(b, m, deterministic)
}
func (m *FileAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileAction.Merge(m, src)
}
func (m *FileAction) XXX_Size() int {
	return xxx_messageInfo_FileAction.Size(m)
}
func (m *FileAction) XXX_DiscardUnknown() {
	xxx_messageInfo_FileAction.DiscardUnknown(m)
}

var xxx_messageInfo_FileAction proto.InternalMessageInfo

func (m *FileAction) GetAction() FileAction_Option {
	if m != nil {
		return m.Action
	}
	return FileAction_SelectFile
}

func (m *FileAction) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type FileProg struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	BytesRead            uint64   `protobuf:"varint,3,opt,name=BytesRead,proto3" json:"BytesRead,omitempty"`
	CurrentLine          uint64   `protobuf:"varint,4,opt,name=CurrentLine,proto3" json:"CurrentLine,omitempty"`
	Progress             float32  `protobuf:"fixed32,5,opt,name=Progress,proto3" json:"Progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileProg) Reset()         { *m = FileProg{} }
func (m *FileProg) String() string { return proto.CompactTextString(m) }
func (*FileProg) ProtoMessage()    {}
func (*FileProg) Descriptor() ([]byte, []int) {
	return fileDescriptor_718985211eb12c86, []int{1}
}

func (m *FileProg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileProg.Unmarshal(m, b)
}
func (m *FileProg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileProg.Marshal(b, m, deterministic)
}
func (m *FileProg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileProg.Merge(m, src)
}
func (m *FileProg) XXX_Size() int {
	return xxx_messageInfo_FileProg.Size(m)
}
func (m *FileProg) XXX_DiscardUnknown() {
	xxx_messageInfo_FileProg.DiscardUnknown(m)
}

var xxx_messageInfo_FileProg proto.InternalMessageInfo

func (m *FileProg) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileProg) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileProg) GetBytesRead() uint64 {
	if m != nil {
		return m.BytesRead
	}
	return 0
}

func (m *FileProg) GetCurrentLine() uint64 {
	if m != nil {
		return m.CurrentLine
	}
	return 0
}

func (m *FileProg) GetProgress() float32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

type File struct {
	PreviousPath         string   `protobuf:"bytes,1,opt,name=PreviousPath,proto3" json:"PreviousPath,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty"`
	FileType             string   `protobuf:"bytes,4,opt,name=FileType,proto3" json:"FileType,omitempty"`
	Size                 uint64   `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	IsDir                bool     `protobuf:"varint,6,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
	UnixTime             int64    `protobuf:"varint,7,opt,name=UnixTime,proto3" json:"UnixTime,omitempty"`
	Contents             []*File  `protobuf:"bytes,8,rep,name=Contents,proto3" json:"Contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_718985211eb12c86, []int{2}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPreviousPath() string {
	if m != nil {
		return m.PreviousPath
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *File) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *File) GetUnixTime() int64 {
	if m != nil {
		return m.UnixTime
	}
	return 0
}

func (m *File) GetContents() []*File {
	if m != nil {
		return m.Contents
	}
	return nil
}

func init() {
	proto.RegisterEnum("FileStructures.FileAction_Option", FileAction_Option_name, FileAction_Option_value)
	proto.RegisterType((*FileAction)(nil), "FileStructures.FileAction")
	proto.RegisterType((*FileProg)(nil), "FileStructures.FileProg")
	proto.RegisterType((*File)(nil), "FileStructures.File")
}

func init() {
	proto.RegisterFile("FileStructures.proto", fileDescriptor_718985211eb12c86)
}

var fileDescriptor_718985211eb12c86 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0xcd, 0x4e, 0xf2, 0x50,
	0x10, 0xfd, 0x4a, 0x4b, 0x29, 0x03, 0x21, 0x64, 0xd2, 0x45, 0xf3, 0xc5, 0x05, 0x76, 0xc5, 0x8a,
	0x18, 0x5c, 0xb9, 0x44, 0x88, 0xc6, 0xc4, 0x1f, 0x72, 0xc1, 0x85, 0x4b, 0x84, 0x89, 0xde, 0x04,
	0x7b, 0xc9, 0xed, 0x2d, 0x11, 0x1f, 0xc4, 0x47, 0xf1, 0x91, 0x7c, 0x0e, 0xef, 0x0f, 0x14, 0x30,
	0xae, 0x98, 0x73, 0x66, 0xee, 0x99, 0x73, 0x86, 0x42, 0x7c, 0xc5, 0x97, 0x34, 0x51, 0xb2, 0x98,
	0xab, 0x42, 0x52, 0xde, 0x5b, 0x49, 0xa1, 0x04, 0xb6, 0x8e, 0xd9, 0xf4, 0xcb, 0x03, 0x30, 0xd4,
	0x60, 0xae, 0xb8, 0xc8, 0xf0, 0x02, 0x42, 0x57, 0x25, 0x5e, 0xc7, 0xeb, 0xb6, 0xfa, 0xa7, 0xbd,
	0x5f, 0x2a, 0xfb, 0xd9, 0xde, 0xc3, 0xca, 0xfc, 0xb0, 0xed, 0x03, 0x44, 0x08, 0xc6, 0x33, 0xf5,
	0x9a, 0x54, 0xf4, 0xc3, 0x3a, 0xb3, 0x75, 0xfa, 0x04, 0xa1, 0x9b, 0xc2, 0x16, 0xc0, 0x84, 0x96,
	0x34, 0x57, 0x46, 0xa0, 0xfd, 0x0f, 0x63, 0x68, 0x5f, 0x93, 0x3a, 0x12, 0x6f, 0x7b, 0xd8, 0x80,
	0xda, 0x60, 0xb1, 0xb0, 0x23, 0x15, 0x6c, 0x42, 0x74, 0x27, 0xd6, 0x64, 0x91, 0x6f, 0x04, 0x46,
	0x5a, 0x40, 0x39, 0x1c, 0xa4, 0x9f, 0x1e, 0x44, 0xa6, 0x1c, 0x4b, 0xf1, 0x82, 0xff, 0x5d, 0x7d,
	0x3f, 0x7b, 0x23, 0x6b, 0xbc, 0xce, 0x4a, 0x6c, 0x7c, 0x4d, 0xf8, 0x07, 0x59, 0x5f, 0x01, 0xb3,
	0x35, 0x9e, 0x40, 0xfd, 0x72, 0xa3, 0x28, 0x67, 0x34, 0x5b, 0x24, 0xbe, 0x6d, 0xec, 0x09, 0xec,
	0x40, 0x63, 0x58, 0x48, 0x49, 0x99, 0xba, 0xe5, 0x19, 0x25, 0x81, 0xed, 0x1f, 0x52, 0x66, 0x9f,
	0xd9, 0xab, 0x0f, 0x92, 0x27, 0x55, 0xdd, 0xae, 0xb0, 0x12, 0xa7, 0xdf, 0x1e, 0x04, 0x66, 0x39,
	0xa6, 0xd0, 0x1c, 0x4b, 0x5a, 0x73, 0x51, 0xe4, 0xf6, 0x30, 0xce, 0xd8, 0x11, 0x67, 0xcc, 0x59,
	0xd3, 0xdb, 0xa3, 0xed, 0x0c, 0xdb, 0x79, 0x7f, 0x7f, 0xc8, 0x5d, 0xc0, 0xe9, 0x66, 0xe5, 0xfc,
	0x6c, 0x03, 0x1a, 0x5c, 0x06, 0xac, 0x1e, 0x04, 0x8c, 0xa1, 0x7a, 0x93, 0x8f, 0xb8, 0x4c, 0x42,
	0x4d, 0x46, 0xcc, 0x01, 0xa3, 0xf2, 0x98, 0xf1, 0xf7, 0x29, 0xd7, 0x1b, 0x6b, 0xba, 0xe1, 0xb3,
	0x12, 0xe3, 0x19, 0x44, 0x43, 0x91, 0x29, 0x9d, 0x30, 0x4f, 0xa2, 0x8e, 0xdf, 0x6d, 0xf4, 0xe3,
	0xbf, 0xfe, 0x7b, 0x56, 0x4e, 0x3d, 0x87, 0xf6, 0x8b, 0x3a, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xbc, 0xac, 0x34, 0xb3, 0x69, 0x02, 0x00, 0x00,
}
