// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CommStructures.proto

package CommStructures

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CommStatus is a representation of the comm
type CommStatus struct {
	Port                 string   `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	Baud                 int32    `protobuf:"varint,2,opt,name=baud,proto3" json:"baud,omitempty"`
	Connected            bool     `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommStatus) Reset()         { *m = CommStatus{} }
func (m *CommStatus) String() string { return proto.CompactTextString(m) }
func (*CommStatus) ProtoMessage()    {}
func (*CommStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c0b99f25164fd39, []int{0}
}

func (m *CommStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommStatus.Unmarshal(m, b)
}
func (m *CommStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommStatus.Marshal(b, m, deterministic)
}
func (m *CommStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommStatus.Merge(m, src)
}
func (m *CommStatus) XXX_Size() int {
	return xxx_messageInfo_CommStatus.Size(m)
}
func (m *CommStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CommStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CommStatus proto.InternalMessageInfo

func (m *CommStatus) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *CommStatus) GetBaud() int32 {
	if m != nil {
		return m.Baud
	}
	return 0
}

func (m *CommStatus) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

// InitComm will be used to initialize the serial comm
type InitComm struct {
	Port                 string   `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	Baud                 int32    `protobuf:"varint,2,opt,name=baud,proto3" json:"baud,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitComm) Reset()         { *m = InitComm{} }
func (m *InitComm) String() string { return proto.CompactTextString(m) }
func (*InitComm) ProtoMessage()    {}
func (*InitComm) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c0b99f25164fd39, []int{1}
}

func (m *InitComm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitComm.Unmarshal(m, b)
}
func (m *InitComm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitComm.Marshal(b, m, deterministic)
}
func (m *InitComm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitComm.Merge(m, src)
}
func (m *InitComm) XXX_Size() int {
	return xxx_messageInfo_InitComm.Size(m)
}
func (m *InitComm) XXX_DiscardUnknown() {
	xxx_messageInfo_InitComm.DiscardUnknown(m)
}

var xxx_messageInfo_InitComm proto.InternalMessageInfo

func (m *InitComm) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *InitComm) GetBaud() int32 {
	if m != nil {
		return m.Baud
	}
	return 0
}

// CommMessage is just a string message it could be a written message or a received message
type CommMessage struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommMessage) Reset()         { *m = CommMessage{} }
func (m *CommMessage) String() string { return proto.CompactTextString(m) }
func (*CommMessage) ProtoMessage()    {}
func (*CommMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c0b99f25164fd39, []int{2}
}

func (m *CommMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommMessage.Unmarshal(m, b)
}
func (m *CommMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommMessage.Marshal(b, m, deterministic)
}
func (m *CommMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommMessage.Merge(m, src)
}
func (m *CommMessage) XXX_Size() int {
	return xxx_messageInfo_CommMessage.Size(m)
}
func (m *CommMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommMessage proto.InternalMessageInfo

func (m *CommMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// WrittenBytes is a receipt for what was written to the comm
type WrittenBytes struct {
	Bytes                int32    `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrittenBytes) Reset()         { *m = WrittenBytes{} }
func (m *WrittenBytes) String() string { return proto.CompactTextString(m) }
func (*WrittenBytes) ProtoMessage()    {}
func (*WrittenBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c0b99f25164fd39, []int{3}
}

func (m *WrittenBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrittenBytes.Unmarshal(m, b)
}
func (m *WrittenBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrittenBytes.Marshal(b, m, deterministic)
}
func (m *WrittenBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrittenBytes.Merge(m, src)
}
func (m *WrittenBytes) XXX_Size() int {
	return xxx_messageInfo_WrittenBytes.Size(m)
}
func (m *WrittenBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_WrittenBytes.DiscardUnknown(m)
}

var xxx_messageInfo_WrittenBytes proto.InternalMessageInfo

func (m *WrittenBytes) GetBytes() int32 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

// Port is a serial port address
type Port struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c0b99f25164fd39, []int{4}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Ports is a list of serial Ports
type Ports struct {
	Ports                []*Port  `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ports) Reset()         { *m = Ports{} }
func (m *Ports) String() string { return proto.CompactTextString(m) }
func (*Ports) ProtoMessage()    {}
func (*Ports) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c0b99f25164fd39, []int{5}
}

func (m *Ports) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ports.Unmarshal(m, b)
}
func (m *Ports) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ports.Marshal(b, m, deterministic)
}
func (m *Ports) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ports.Merge(m, src)
}
func (m *Ports) XXX_Size() int {
	return xxx_messageInfo_Ports.Size(m)
}
func (m *Ports) XXX_DiscardUnknown() {
	xxx_messageInfo_Ports.DiscardUnknown(m)
}

var xxx_messageInfo_Ports proto.InternalMessageInfo

func (m *Ports) GetPorts() []*Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func init() {
	proto.RegisterType((*CommStatus)(nil), "CommStructures.CommStatus")
	proto.RegisterType((*InitComm)(nil), "CommStructures.InitComm")
	proto.RegisterType((*CommMessage)(nil), "CommStructures.CommMessage")
	proto.RegisterType((*WrittenBytes)(nil), "CommStructures.WrittenBytes")
	proto.RegisterType((*Port)(nil), "CommStructures.Port")
	proto.RegisterType((*Ports)(nil), "CommStructures.Ports")
}

func init() { proto.RegisterFile("CommStructures.proto", fileDescriptor_6c0b99f25164fd39) }

var fileDescriptor_6c0b99f25164fd39 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x5a, 0xd3, 0xf6, 0x8a, 0x18, 0xac, 0x0c, 0x1e, 0x18, 0x22, 0x0b, 0x89, 0x88,
	0xa1, 0x43, 0xfb, 0x0f, 0x60, 0x62, 0x40, 0x42, 0x66, 0x60, 0x4e, 0xe2, 0x13, 0xea, 0x10, 0xbb,
	0xf2, 0x9d, 0x07, 0xfe, 0x3d, 0x3a, 0xbb, 0x15, 0x82, 0x89, 0xed, 0xbd, 0xa7, 0xcf, 0xcf, 0xa7,
	0x07, 0xed, 0x73, 0x9c, 0xe7, 0x77, 0x4e, 0x79, 0xe2, 0x9c, 0x90, 0x76, 0xa7, 0x14, 0x39, 0xea,
	0xdb, 0xdf, 0xa9, 0x75, 0x00, 0x35, 0x19, 0x38, 0x93, 0xd6, 0xb0, 0x3c, 0xc5, 0xc4, 0xa6, 0xe9,
	0x9a, 0x7e, 0xe3, 0x8a, 0x96, 0x6c, 0x1c, 0xb2, 0x37, 0x57, 0x5d, 0xd3, 0x2b, 0x57, 0xb4, 0xbe,
	0x83, 0xcd, 0x14, 0x43, 0xc0, 0x89, 0xd1, 0x9b, 0x45, 0xd7, 0xf4, 0x6b, 0xf7, 0x13, 0xd8, 0x3d,
	0xac, 0x5f, 0xc2, 0x91, 0xa5, 0xf7, 0xbf, 0x8d, 0xf6, 0x01, 0xb6, 0xc2, 0xbf, 0x22, 0xd1, 0xf0,
	0x89, 0xda, 0xc0, 0x6a, 0xae, 0xf2, 0xfc, 0xf2, 0x62, 0xed, 0x3d, 0xdc, 0x7c, 0xa4, 0x23, 0x33,
	0x86, 0xa7, 0x2f, 0x46, 0xd2, 0x2d, 0xa8, 0x51, 0x44, 0xe1, 0x94, 0xab, 0xc6, 0x76, 0xb0, 0x7c,
	0x93, 0xaf, 0x0c, 0xac, 0x06, 0xef, 0x13, 0x12, 0x5d, 0x7a, 0xce, 0xd6, 0x1e, 0x40, 0x09, 0x41,
	0xfa, 0x11, 0x94, 0x5c, 0x25, 0xc0, 0xa2, 0xdf, 0xee, 0xdb, 0xdd, 0x9f, 0xdd, 0x84, 0x72, 0x15,
	0x19, 0xaf, 0xcb, 0x88, 0x87, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0xfb, 0x1e, 0x39, 0x5c,
	0x01, 0x00, 0x00,
}
