FROM flotilla_root:latest

RUN mkdir -p $HOME/gcode/

WORKDIR $FLOTILLA_DIR/Flotilla_File_Manager/
COPY . .
RUN go build -ldflags "-X 'github.com/Ximidar/Flotilla/CommonTools/versioning.Version=0.0.1' -X 'github.com/Ximidar/Flotilla/CommonTools/versioning.CompiledBy=Matt Pedler' -X 'github.com/Ximidar/Flotilla/CommonTools/versioning.CompiledDate=`date '+%d %b %y at %H:%M:%S %p'`'" -o FlotillaFileManager
#RUN make

CMD ./FlotillaFileManager