FROM ximidar/flotilla_root:latest as flot
WORKDIR $FLOTILLA_DIR/FlotillaWeb
COPY . .
RUN go build -ldflags "-X 'github.com/Ximidar/Flotilla/CommonTools/versioning.Version=0.0.1' -X 'github.com/Ximidar/Flotilla/CommonTools/versioning.CompiledBy=Matt Pedler' -X 'github.com/Ximidar/Flotilla/CommonTools/versioning.CompiledDate=`date '+%d %b %y at %H:%M:%S %p'`'" -o FlotillaWeb

# Goals of this dockerfile. Set up for Go and a website
FROM node:lts-alpine

RUN mkdir code
WORKDIR ./code

# install depends
RUN npm install -g @vue/cli
RUN npm install -g @vue/cli-service-global
# copy over all files 
COPY . .
RUN npm install

# Expose port
EXPOSE 8080
WORKDIR ./src
COPY --from=flot FlotillaWeb .
CMD ["./FlotillaWeb", "&&", "npm", "run", "serve"]

