// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TemperatureStructures.proto

package TemperatureStructures

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Temperature struct {
	Tool                 string   `protobuf:"bytes,1,opt,name=Tool,proto3" json:"Tool,omitempty"`
	Temp                 int32    `protobuf:"varint,2,opt,name=Temp,proto3" json:"Temp,omitempty"`
	Target               int32    `protobuf:"varint,3,opt,name=Target,proto3" json:"Target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Temperature) Reset()         { *m = Temperature{} }
func (m *Temperature) String() string { return proto.CompactTextString(m) }
func (*Temperature) ProtoMessage()    {}
func (*Temperature) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c79f9fffcd23181, []int{0}
}

func (m *Temperature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Temperature.Unmarshal(m, b)
}
func (m *Temperature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Temperature.Marshal(b, m, deterministic)
}
func (m *Temperature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Temperature.Merge(m, src)
}
func (m *Temperature) XXX_Size() int {
	return xxx_messageInfo_Temperature.Size(m)
}
func (m *Temperature) XXX_DiscardUnknown() {
	xxx_messageInfo_Temperature.DiscardUnknown(m)
}

var xxx_messageInfo_Temperature proto.InternalMessageInfo

func (m *Temperature) GetTool() string {
	if m != nil {
		return m.Tool
	}
	return ""
}

func (m *Temperature) GetTemp() int32 {
	if m != nil {
		return m.Temp
	}
	return 0
}

func (m *Temperature) GetTarget() int32 {
	if m != nil {
		return m.Target
	}
	return 0
}

func init() {
	proto.RegisterType((*Temperature)(nil), "TemperatureStructures.Temperature")
}

func init() {
	proto.RegisterFile("TemperatureStructures.proto", fileDescriptor_8c79f9fffcd23181)
}

var fileDescriptor_8c79f9fffcd23181 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x0e, 0x49, 0xcd, 0x2d,
	0x48, 0x2d, 0x4a, 0x2c, 0x29, 0x2d, 0x4a, 0x0d, 0x2e, 0x29, 0x2a, 0x4d, 0x06, 0x31, 0x8a, 0xf5,
	0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x44, 0xb1, 0x4a, 0x2a, 0xf9, 0x72, 0x71, 0x23, 0x49, 0x08,
	0x09, 0x71, 0xb1, 0x84, 0xe4, 0xe7, 0xe7, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x60, 0x31, 0xa0, 0x12, 0x09, 0x26, 0xa0, 0x18, 0x6b, 0x10, 0x98, 0x2d, 0x24, 0xc6, 0xc5, 0x16,
	0x92, 0x58, 0x94, 0x9e, 0x5a, 0x22, 0xc1, 0x0c, 0x16, 0x85, 0xf2, 0x92, 0xd8, 0xc0, 0x96, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x38, 0x98, 0xaf, 0xa3, 0x8b, 0x00, 0x00, 0x00,
}
