name: flotilla # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: 3D printer server software
description: |
  Flotilla is a 3D printer server designed to be a simple set up
  and run software package. Currently only tested with Marlin.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  # flotcli
  cli:
    command: bin/Flotilla_CLI
    plugs:
      - network
  
  # nats-server
  nats:
    command: bin/nats-server
    daemon: simple
    plugs:
      - network
      - network-bind
  
  # status
  status:
    command: bin/FlotillaStatus
    daemon: simple
    plugs:
      - network
  
  # file manager
  file-manager:
    command: bin/Flotilla_File_Manager
    daemon: simple
    plugs:
      - network
      - home
      - io-ports-control
  
  # commango
  commango:
    command: bin/Commango
    daemon: simple
    plugs:
      - network
      - io-ports-control
      - serial-port
  
  # web
  # flot-web:
  #   command: bin/FlotillaWeb
  #   daemon: simple


parts:
  flot-root:
    plugin: go
    go-packages:
      - github.com/Ximidar/Flotilla/FlotillaStatus
      - github.com/Ximidar/Flotilla/Commango
      - github.com/Ximidar/Flotilla/Flotilla_CLI
      - github.com/Ximidar/Flotilla/Flotilla_File_Manager
      - github.com/Ximidar/Flotilla/FlotillaWeb
    source: .
    go-importpath: github.com/Ximidar/Flotilla
  
  nats-server:
    plugin: go
    source: https://github.com/nats-io/nats-server
    source-type: git
    go-importpath: github.com/nats-io/nats-server
    go-packages:
      - github.com/nats-io/nats-server
